#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(17, GPIO.OUT)

while True:
   GPIO.output(6,1)
   time.sleep(.2)
   GPIO.output(6,0)
   time.sleep(.2)
GPIO.cleanup()


