#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
GPIO.setup(17, GPIO.OUT)

while True:
   GPIO.output(6,0)
   GPIO.output(22,0)
   GPIO.output(17,0)
   GPIO.output(19,0)
   time.sleep(.25)
   GPIO.output(6,1)
   GPIO.output(19,1)
   GPIO.output(22,1)
   GPIO.output(17,1)
   time.sleep(.25)
GPIO.cleanup()


